DeeEmm/DIY-Flow-Bench

- ESP32/DIY-Flow-Bench/API.cpp
- ESP32/DIY-Flow-Bench/API.h
- ESP32/DIY-Flow-Bench/DIY-Flow-Bench.ino
- ESP32/DIY-Flow-Bench/calculations.cpp
- ESP32/DIY-Flow-Bench/calculations.h
- ESP32/DIY-Flow-Bench/configuration.h
- ESP32/DIY-Flow-Bench/mafData/ACDELCO_92281162.cpp
- ESP32/DIY-Flow-Bench/sensors.cpp
- ESP32/DIY-Flow-Bench/sensors.h
- ESP32/DIY-Flow-Bench/structs.h
- ESP32/DIY-Flow-Bench/webserver.cpp
- ESP32/DIY-Flow-Bench/webserver.h
- docs/changelog
Build #         - Description of Change
31012301        - Fixed MAF unit error
- Fix Ref depression unit error
- Added bench running check to adjusted flow calc
23012701        - Renamed TASKgetBenchData to TASKgetSensorData
23012501        - Fixed checksum (CRC32)     
23012401        - Updated ESP library names for Arduino platform
> Build 31012301

- ESP32/DIY-Flow-Bench/calculations.cpp
- ESP32/DIY-Flow-Bench/configuration.h
- ESP32/DIY-Flow-Bench/data/index.html
- ESP32/DIY-Flow-Bench/src/index.html
- ESP32/DIY-Flow-Bench/src/javascript.js
- ESP32/DIY-Flow-Bench/webserver.cpp
- docs/changelog
```
Build #         - Description of Change
23041301        - Added graph image capture
- General code tidy
```
> Build 23041202

- ESP32/DIY-Flow-Bench/DIY-Flow-Bench.ino
- ESP32/DIY-Flow-Bench/configuration.h
- ESP32/DIY-Flow-Bench/pins.h
- ESP32/DIY-Flow-Bench/sensors.cpp
- ESP32/DIY-Flow-Bench/webserver.cpp
- ESP32/DIY-Flow-Bench/webserver.h
- docs/changelog
- SD Card methods validated
- Missing line terminator #187
- Changed unused pins to '-1' in pins.h
Tested SD card functionality on V2.3 shield.
SD card methods withiin webserver class validated as working
> Build 24110201

- ESP32/DIY-Flow-Bench/configuration.h
MV_TRIMPOT had not been zeros out from my last pull request for Pref, Diff and Pitot
> MV_TRIMPOT had not been zeroed out from my last pull request

- ESP32/DIY-Flow-Bench/configuration.h
- ESP32/DIY-Flow-Bench/webserver.cpp
- docs/changelog
- platformio.ini
- Fixed flow thresholds to allow negative flow values in GUI
- Updated changelog to include decriptions for changes made in KirikauKiwis PR...
24110301        - Added M5Stack Core2 Support
- Added M5Stack Tube Pressure sensor
- Fixed line endings in sensors.cpp
- Fixed bug in VelocityToVolumetric method
> Build 24110302

- ESP32/DIY-Flow-Bench/calculations.cpp
- ESP32/DIY-Flow-Bench/configuration.h
- docs/changelog
> Correction to equation

- ESP32/DIY-Flow-Bench/configuration.h
- ESP32/DIY-Flow-Bench/data/index.html
- ESP32/DIY-Flow-Bench/src/index.html
- ESP32/DIY-Flow-Bench/src/javascript.js
- ESP32/DIY-Flow-Bench/structs.h
- ESP32/DIY-Flow-Bench/webserver.cpp
- docs/changelog
- #180 Added ability to truncate / round flow values in GUI
> Build 24110402

- ESP32/DIY-Flow-Bench/configuration.h
- ESP32/DIY-Flow-Bench/webserver.cpp
- docs/changelog
- Added HTTP API Call for JSON Data
> Build 24110403

- ESP32/DIY-Flow-Bench/DIY-Flow-Bench.ino
- ESP32/DIY-Flow-Bench/structs.h
- ESP32/DIY-Flow-Bench/version.h
- ESP32/DIY-Flow-Bench/webserver.cpp
- docs/changelog
- Changed Pdiff and Pitot GUI vals from kPa to H2O
> Build 24110704        - Changed Pdiff and Pitot GUI vals from kPa to H2O

- ESP32/DIY-Flow-Bench/API.cpp
- ESP32/DIY-Flow-Bench/hardware.cpp
- ESP32/DIY-Flow-Bench/sensors.cpp
- docs/changelog
Build 24110704        - Updated calls to #include "version.h"
> Build 24110704        - Updated calls to #include "version.h"

- ESP32/DIY-Flow-Bench/DIY-Flow-Bench.ino
- ESP32/DIY-Flow-Bench/calculations.cpp
- ESP32/DIY-Flow-Bench/calculations.h
- ESP32/DIY-Flow-Bench/constants.h
- ESP32/DIY-Flow-Bench/data/index.html
- ESP32/DIY-Flow-Bench/sensors.cpp
- ESP32/DIY-Flow-Bench/src/index.html
- ESP32/DIY-Flow-Bench/src/javascript.js
- ESP32/DIY-Flow-Bench/src/style.css
- ESP32/DIY-Flow-Bench/structs.h
- ESP32/DIY-Flow-Bench/version.h
- ESP32/DIY-Flow-Bench/webserver.cpp
- docs/changelog
24111102        - #212 Modal Window cropped
24111101        - #208 Added SCFM
- #212 Display issues
- Redirect to Main after config change
> Build 24111102 - Added SCFM

- ESP32/DIY-Flow-Bench/sensors.cpp
- ESP32/DIY-Flow-Bench/version.h
- docs/changelog
24111103  - #217 Scaled MAF housing returns O.O.R. value
> 24111103 - #217 Scaled MAF housing returns O.O.R. value

- ESP32/DIY-Flow-Bench/DIY-Flow-Bench.ino
- ESP32/DIY-Flow-Bench/data/index.html
- ESP32/DIY-Flow-Bench/src/index.html
- ESP32/DIY-Flow-Bench/structs.h
- ESP32/DIY-Flow-Bench/version.h
- ESP32/DIY-Flow-Bench/webserver.cpp
- docs/changelog
24111107 - #222 Adjusted standard flow
> 24111107 - #222 Adjusted standard flow

- ESP32/DIY-Flow-Bench/DIY-Flow-Bench.ino
- ESP32/DIY-Flow-Bench/calculations.cpp
- ESP32/DIY-Flow-Bench/calculations.h
- ESP32/DIY-Flow-Bench/constants.h
- ESP32/DIY-Flow-Bench/data/index.html
- ESP32/DIY-Flow-Bench/language/EN_language.json
- ESP32/DIY-Flow-Bench/src/index.html
- ESP32/DIY-Flow-Bench/structs.h
- ESP32/DIY-Flow-Bench/version.json
- ESP32/DIY-Flow-Bench/webserver.cpp
- docs/changelog
- gulpfile.js
24112301 - #158 Add capture datatype selection
> 24112301 - #158 Add capture datatype selection

- ESP32/DIY-Flow-Bench/version.json
- ESP32/DIY-Flow-Bench/webserver.cpp
- docs/changelog
24112401 - #158 Correction to output
> 24112401 - #158 Correction to output

- ESP32/DIY-Flow-Bench/API.cpp
- ESP32/DIY-Flow-Bench/DIY-Flow-Bench.ino
- ESP32/DIY-Flow-Bench/calibration.cpp
- ESP32/DIY-Flow-Bench/data/index.html
- ESP32/DIY-Flow-Bench/datahandler.cpp
- ESP32/DIY-Flow-Bench/sensors.cpp
- ESP32/DIY-Flow-Bench/src/index.html
- ESP32/DIY-Flow-Bench/src/javascript.js
- ESP32/DIY-Flow-Bench/src/style.css
- ESP32/DIY-Flow-Bench/system.h
- ESP32/DIY-Flow-Bench/version.json
- ESP32/DIY-Flow-Bench/webserver.cpp
- docs/changelog
- #213 Pitot / differential zeroing
- #254 Report sensor voltage to API
- Cookie to remember tile status
> 24112402 - #213 Pitot / differential zeroing

- ESP32/DIY-Flow-Bench/API.cpp
- ESP32/DIY-Flow-Bench/version.json
> 239-Update_Serial_API_calls

- ESP32/DIY-Flow-Bench/data/index.html
- ESP32/DIY-Flow-Bench/datahandler.cpp
- ESP32/DIY-Flow-Bench/src/index.html
- ESP32/DIY-Flow-Bench/src/javascript.js
- ESP32/DIY-Flow-Bench/version.json
- docs/changelog
Build 24112502
- #157 Updated datagraph settings
- Capture radio retains selection
> Issue-157-LiftGraph_png_file_has_blank_data

- ESP32/DIY-Flow-Bench/sensors.cpp
- ESP32/DIY-Flow-Bench/version.json
- docs/changelog
24112503 - #213 Pitot offset error
> 213gui-pitot-display-changes

- ESP32/DIY-Flow-Bench/datahandler.cpp
Stopping the temp server and adding a delay before the reset has resolved the issue
> Changes to datahandler.cpp to stop the web server before it is reset.
